name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3.0.0
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Gradle build
        run: |
          ./gradlew build
          # Get the Git hash
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          echo "git_hash=$git_hash" >> $GITHUB_ENV

      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
          name: vane-${{ env.git_hash }}.jar
          path: build/libs/vane-dev.jar